import 'dart:typed_data'; // Required for Uint8List
import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/cetaklaporan_model.dart';

class LaporanPdfGenerator {
  static Future<void> generateAndPrintPdf(
    List<LaporanItem> items,
    DateTime dariTanggal,
    DateTime sampaiTanggal,
    String kategori,
  ) async {
    print("--- [1] STARTING PROCESS ---");
    
    final pdf = pw.Document();
    final formatCurrency = NumberFormat.currency(
      locale: 'id_ID',
      symbol: 'Rp ',
      decimalDigits: 0,
    );

    // 1. Load Fonts (Pre-load them safely)
    pw.Font font;
    pw.Font boldFont;

    try {
      print("--- [2] LOADING FONTS ---");
      final fontData = await rootBundle.load('assets/fonts/Poppins-Regular.ttf');
      font = pw.Font.ttf(fontData);

      final boldFontData = await rootBundle.load('assets/fonts/Poppins-Bold.ttf');
      boldFont = pw.Font.ttf(boldFontData);
      print("--- [2] FONTS LOADED ---");
    } catch (e) {
      print("--- [!] FONT ERROR: $e ---");
      // Fallback to standard fonts if assets fail
      font = pw.Font.courier();
      boldFont = pw.Font.courierBold();
    }

    // 2. Build PDF Structure
    print("--- [3] BUILDING PDF PAGE ---");
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          double total = 0;
          for (var item in items) {
            total += (item.tipe == LaporanItemTipe.pemasukan)
                ? item.nominal
                : -item.nominal;
          }

          return [
            _buildHeader(
                context, dariTanggal, sampaiTanggal, kategori, font, boldFont),
            _buildTable(context, items, font, boldFont, formatCurrency),
            pw.Divider(thickness: 1, borderStyle: pw.BorderStyle.dashed),
            _buildTotals(context, total, font, boldFont, formatCurrency),
          ];
        },
      ),
    );

    // 3. CRITICAL FIX: Generate bytes BEFORE calling layoutPdf
    // This prevents the "Preparing" spinner from timing out.
    print("--- [4] GENERATING BYTES (Heavy Task) ---");
    final Uint8List bytes = await pdf.save();
    print("--- [4] BYTES GENERATED: ${bytes.length} bytes ---");

    // 4. Hand off to Printer
    print("--- [5] OPENING PRINT PREVIEW ---");
    await Printing.layoutPdf(
      // Simple callback that just returns the already-generated bytes
      onLayout: (PdfPageFormat format) async => bytes,
      name: 'Laporan_Keuangan_${DateFormat('dd-MM-yyyy').format(DateTime.now())}',
    );
    print("--- [6] DONE ---");
  }

  static pw.Widget _buildHeader(
    pw.Context context,
    DateTime dariTanggal,
    DateTime sampaiTanggal,
    String kategori,
    pw.Font font,
    pw.Font boldFont,
  ) {
    final formatDate = DateFormat('dd MMMM yyyy', 'id_ID');
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Laporan Keuangan',
          style: pw.TextStyle(font: boldFont, fontSize: 20),
        ),
        pw.SizedBox(height: 8),
        pw.Text(
          'Periode: ${formatDate.format(dariTanggal)} - ${formatDate.format(sampaiTanggal)}',
          style: pw.TextStyle(font: font, fontSize: 12),
        ),
        pw.Text(
          'Kategori: $kategori',
          style: pw.TextStyle(font: font, fontSize: 12),
        ),
        pw.SizedBox(height: 20),
      ],
    );
  }

  static pw.Widget _buildTable(
    pw.Context context,
    List<LaporanItem> items,
    pw.Font font,
    pw.Font boldFont,
    NumberFormat formatCurrency,
  ) {
    final headers = [
      'Tanggal',
      'Nama Item',
      'Kategori',
      'Pemasukan',
      'Pengeluaran'
    ];

    final data = items.map((item) {
      return [
        item.tanggalFormatted,
        item.nama,
        item.kategori,
        item.tipe == LaporanItemTipe.pemasukan
            ? formatCurrency.format(item.nominal)
            : '-',
        item.tipe == LaporanItemTipe.pengeluaran
            ? formatCurrency.format(item.nominal)
            : '-',
      ];
    }).toList();

    return pw.Table.fromTextArray(
      headers: headers,
      data: data,
      headerStyle: pw.TextStyle(font: boldFont, fontSize: 10),
      cellStyle: pw.TextStyle(font: font, fontSize: 10),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.centerLeft,
        2: pw.Alignment.centerLeft,
        3: pw.Alignment.centerRight,
        4: pw.Alignment.centerRight,
      },
    );
  }

  static pw.Widget _buildTotals(
    pw.Context context,
    double total,
    pw.Font font,
    pw.Font boldFont,
    NumberFormat formatCurrency,
  ) {
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Text(
            'Total: ${formatCurrency.format(total)}',
            style: pw.TextStyle(font: boldFont, fontSize: 14),
          ),
        ],
      ),
    );
  }
}